site_name: るいもの戯れ言
site_url: https://ruimo.github.io/ruimo-blog/

nav:
  - '': index.md
  - Blog:
    - blog/index.md
  - DIY:
    - diy/index.md
    - UV-211 アンプ製作記: diy/uv211.md
    - ジョイスティックを作ろう: diy/joystick.md
    - 自動電源offスイッチ: https://ruimo.github.io/auto_power_off/
    - ATtiny10マイコン: https://ruimo.github.io/attiny10-blink/
    - CH32V003マイコン: https://ruimo.github.io/ch32v003try/
    - 万能導通テスター: https://r8c-m1x0a.github.io/univ_tester/
    - オーディオスイッチャー: https://ruimo.github.io/audioswitcher/
  - Tools:
    - tools/index.md
    - tools/genbar.md
  - Piano:
     - Beethoven:
       - Piano Sonata:
          - piano/Beethoven/PianoSonata/index.md
          - piano/Beethoven/PianoSonata/no01/index.md
          - piano/Beethoven/PianoSonata/no02/index.md
          - piano/Beethoven/PianoSonata/no03/index.md
          - piano/Beethoven/PianoSonata/no04/index.md
          - piano/Beethoven/PianoSonata/no05/index.md
          - piano/Beethoven/PianoSonata/no06/index.md
          - piano/Beethoven/PianoSonata/no07/index.md
          - piano/Beethoven/PianoSonata/no08/index.md
          - piano/Beethoven/PianoSonata/no09/index.md
          - piano/Beethoven/PianoSonata/no10/index.md
          - piano/Beethoven/PianoSonata/no11/index.md
          - piano/Beethoven/PianoSonata/no12/index.md
          - piano/Beethoven/PianoSonata/no13/index.md
          - piano/Beethoven/PianoSonata/no14/index.md
          - piano/Beethoven/PianoSonata/no15/index.md
          - piano/Beethoven/PianoSonata/no16/index.md
          - piano/Beethoven/PianoSonata/no17/index.md
          - piano/Beethoven/PianoSonata/no18/index.md
          - piano/Beethoven/PianoSonata/no19/index.md
          - piano/Beethoven/PianoSonata/no20/index.md
          - piano/Beethoven/PianoSonata/no21/index.md
          - piano/Beethoven/PianoSonata/no22/index.md
          - piano/Beethoven/PianoSonata/no23/index.md
          - piano/Beethoven/PianoSonata/no24/index.md
          - piano/Beethoven/PianoSonata/no25/index.md
          - piano/Beethoven/PianoSonata/no26/index.md
          - piano/Beethoven/PianoSonata/no27/index.md
          - piano/Beethoven/PianoSonata/no28/index.md
          - piano/Beethoven/PianoSonata/no29/index.md
     - Chopin:
       - Nocturne:
          - piano/Chopin/Nocturne/index.md
       - Prelude:
          - piano/Chopin/Prelude/index.md
       - Piano Misc:
          - piano/Chopin/PianoMisc/index.md
plugins:
  - blog:
      categories: true
  - search
  - rss:
      abstract_chars_count: 160  # 概要の文字数
      date_from_meta:
        as_creation: date        # 作成日としてmeta情報の'date'を使用
        as_update: lastmod       # 更新日としてmeta情報の'lastmod'を使用
      image: https://ruimo.github.io/ruimo-blog/assets/images/logo.gif
      categories:
        - categories
        - tags
      comments_path: "#__comments"  # コメントセクションへのリンク（オプション）
theme:
  favicon: assets/images/favicon.ico
  custom_dir: docs/templates
  language: ja
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
  features:
    - navigation.footer
    - content.code.copy
    - navigation.indexes
markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - mdx_math:
      enable_dollar_delimiter: true
extra_javascript: 
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML
extra_css:
  - stylesheets/extra.css
