site_name: るいもの戯れ言

nav:
  - index.md
  - Blog:
    - blog/index.md
  - others.md
plugins:
  - blog
theme:
  custom_dir: 'docs/templates'
  language: ja
  name: material
  palette:
    scheme: slate
  features:
    - navigation.footer
    - content.code.copy
    - navigation.indexes
markdown_extensions:
  - md_in_html
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - mdx_math:
      enable_dollar_delimiter: true
extra_javascript: 
  - http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML
