site_name: るいもの戯れ言
site_url: https://ruimo.github.io/ruimo-blog/

nav:
  - Blog:
    - blog/index.md
  - DIY:
    - UV-211 アンプ製作記: https://www.ruimo.com/static/diy/tube/211/index.html
    - ジョイスティックを作ろう: https://www.ruimo.com/static/diy/joystick/index.html
  - Tools:
    - tools/genbar.md
plugins:
  - blog
  - rss:
      abstract_chars_count: 160  # 概要の文字数
      date_from_meta:
        as_creation: date        # 作成日としてmeta情報の'date'を使用
        as_update: lastmod       # 更新日としてmeta情報の'lastmod'を使用
      image: https://example.com/image.png  # デフォルトアイキャッチ画像
      categories:
        - categories
        - tags
      comments_path: "#__comments"  # コメントセクションへのリンク（オプション）
      use_directory_url: true
theme:
  favicon: assets/images/favicon.ico
  custom_dir: 'docs/templates'
  language: ja
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
  features:
    - navigation.footer
    - content.code.copy
    - navigation.indexes
markdown_extensions:
  - md_in_html
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - mdx_math:
      enable_dollar_delimiter: true
extra_javascript: 
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML
extra_css:
  - stylesheets/extra.css
