site_name: るいもの戯れ言
site_url: https://ruimo.github.io/ruimo-blog/

nav:
  - '': index.md
  - Blog:
    - blog/index.md
  - DIY:
    - diy/index.md
    - UV-211 アンプ製作記: diy/uv211.md
    - ジョイスティックを作ろう: diy/joystick.md
    - 自動電源offスイッチ: https://ruimo.github.io/auto_power_off/
    - ATtiny10マイコン: https://ruimo.github.io/attiny10-blink/
    - CH32V003マイコン: https://ruimo.github.io/ch32v003try/
    - 万能導通テスター: https://r8c-m1x0a.github.io/univ_tester/
    - オーディオスイッチャー: https://ruimo.github.io/audioswitcher/
  - Tools:
    - tools/index.md
    - tools/genbar.md
plugins:
  - blog:
      categories: true
  - search
  - rss:
      abstract_chars_count: 160  # 概要の文字数
      date_from_meta:
        as_creation: date        # 作成日としてmeta情報の'date'を使用
        as_update: lastmod       # 更新日としてmeta情報の'lastmod'を使用
      image: https://ruimo.github.io/ruimo-blog/assets/images/logo.gif
      categories:
        - categories
        - tags
      comments_path: "#__comments"  # コメントセクションへのリンク（オプション）
theme:
  favicon: assets/images/favicon.ico
  custom_dir: 'docs/templates'
  language: ja
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
  features:
    - navigation.footer
    - content.code.copy
    - navigation.indexes
markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - mdx_math:
      enable_dollar_delimiter: true
extra_javascript: 
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML
  - javascripts/extra.js
extra_css:
  - stylesheets/extra.css
